/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gofish.swing.player;

import gofish.exception.GameStoppedException;
import gofish.model.Card;
import gofish.model.Player;
import gofish.swing.CardLabel;
import gofish.swing.CompleteLabel;
import gofish.swing.SwingUtils;
import java.awt.Color;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.BalloonTipStyle;
import net.java.balloontip.styles.RoundedBalloonStyle;

/**
 *
 * @author amitayh
 */
public class PlayerPanel extends javax.swing.JPanel {
    
    final private static Color PLAYING_BACKGROUND = new Color(0xFFFEDF);
    
    final private static BalloonTipStyle BALLOON_STYLE =
        new RoundedBalloonStyle(5 ,5, Color.WHITE, Color.BLACK);
    
    private Player player;

    /**
     * Creates new form PlayerPanel
     */
    public PlayerPanel(Player player) {
        initComponents();
        
        this.player = player;
        String name = SwingUtils.bold(player.getName());
        nameLabel.setText(name);
        updatePanels();
    }
    
    public void isPlaying() {
        setBackground(PLAYING_BACKGROUND);
    }
    
    public void isNotPlaying() {
        setBackground(null);
    }
    
    public void say(String message) {
        BalloonTip tip = new BalloonTip(nameLabel, message, BALLOON_STYLE, false);
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            throw new GameStoppedException(e);
        } finally {
            tip.closeBalloon();
        }
    }
    
    public Player getPlayer() {
        return player;
    }
    
    public final void updatePanels() {
        updateCompletePanel();
        updateHandPanel();
    }
    
    public void updateCompletePanel() {
        completePanel.removeAll();
        int numComplete = player.getCompleteSeries().size();
        for (int i = 0; i < numComplete; i++) {
            completePanel.add(new CompleteLabel());
        }
    }
    
    public void updateHandPanel() {
        handPanel.removeAll();
        for (Card card : player.getHand()) {
            CardLabel cardLabel = new CardLabel(card);
            if (player.getType() == Player.Type.HUMAN) {
                cardLabel.setRevealed(true);
            }
            handPanel.add(cardLabel);
        }
        handPanel.repaint();
    }
    
    public void playerOut() {
        setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        completePanel = new javax.swing.JPanel();
        handPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        topPanel.setOpaque(false);
        topPanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gofish/resources/images/user.png"))); // NOI18N
        nameLabel.setText("Player Name");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nameLabel.setPreferredSize(new java.awt.Dimension(84, 84));
        nameLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        topPanel.add(nameLabel, java.awt.BorderLayout.LINE_START);

        completePanel.setOpaque(false);
        completePanel.setPreferredSize(new java.awt.Dimension(100, 70));
        completePanel.setRequestFocusEnabled(false);
        topPanel.add(completePanel, java.awt.BorderLayout.CENTER);

        add(topPanel, java.awt.BorderLayout.NORTH);

        handPanel.setOpaque(false);
        handPanel.setPreferredSize(new java.awt.Dimension(100, 115));
        handPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, -55, 5));
        add(handPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel completePanel;
    private javax.swing.JPanel handPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

}
