/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gofish.swing.player;

import gofish.model.Card;
import gofish.model.Player;
import gofish.swing.CardLabel;
import gofish.swing.SwingUtils;
import java.awt.Color;
import net.java.balloontip.BalloonTip;
import net.java.balloontip.styles.BalloonTipStyle;
import net.java.balloontip.styles.RoundedBalloonStyle;

/**
 *
 * @author amitayh
 */
public class PlayerPanel extends javax.swing.JPanel {
    
    final private static Color PLAYING_BACKGROUND = new Color(0xFFFEDF);
    
    final private static BalloonTipStyle BALLOON_STYLE =
        new RoundedBalloonStyle(5 ,5, Color.WHITE, Color.BLACK);
    
    private Player player;

    /**
     * Creates new form PlayerPanel
     */
    public PlayerPanel(Player player) {
        initComponents();
        
        this.player = player;
        String name = SwingUtils.bold(player.getName());
        nameLabel.setText(name);
        updateHandPanel(player);
    }
    
    public void isPlaying() {
        setBackground(PLAYING_BACKGROUND);
    }
    
    public void isNotPlaying() {
        setBackground(null);
    }
    
    public void say(String message) {
        BalloonTip tip = new BalloonTip(nameLabel, message, BALLOON_STYLE, false);
    }
    
    private void updateHandPanel(Player player) {
        for (Card card : player.getHand()) {
            CardLabel cardLabel = new CardLabel(card);
            if (player.getType() == Player.Type.HUMAN) {
                cardLabel.setRevealed(true);
            }
            handPanel.add(cardLabel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        handPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gofish/resources/images/user.png"))); // NOI18N
        nameLabel.setText("Player Name");
        add(nameLabel, java.awt.BorderLayout.CENTER);

        handPanel.setPreferredSize(new java.awt.Dimension(400, 115));
        handPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, -55, 5));
        add(handPanel, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel handPanel;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

}
